# compse.yml

version: '3'

services:
      
  api:
      image: my_api
      build:
       context:
          ./API
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
        - "traefik.http.services.api.loadbalancer.server.port=7070"

  site-a:
      image: web
      build:
        context:
          ./web
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.site-a.rule=Host(`localhost`)"
        - "traefik.http.services.static-web.loadbalancer.server.port=80"


  reverse-proxy:
        # The official v2 Traefik docker image
    image: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: 
        --api.insecure=true
        --providers.docker
    ports:
        # The HTTP port
        - "80:80"
        - "443:443"
        # The Web UI (enabled by --api.insecure=true)
        - "8080:8080"

    volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock