# compse.yml

version: '3'

services:
      
  api:
      image: my_api
      build:
       context:
          ./API
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`localhost`) && PathPrefix(`/api`)"
        - "traefik.http.services.api.loadbalancer.sticky=true"
        - "traefik.http.services.api.loadbalancer.server.port=7070"
        - "traefik.http.services.api.loadbalancer.sticky.cookie.name=superCookie"
        - "traefik.http.services.api.loadbalancer.sticky.cookie.secure=true"
        - "traefik.http.routers.api.entrypoints=http,https"
        - "traefik.http.routers.api.tls=true"

      deploy:
        replicas: 3

  site-a:
      image: web
      build:
        context:
          ./web

      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.site-a.rule=Host(`localhost`)"
        - "traefik.http.services.site-a.loadbalancer.server.port=80"
        - "traefik.http.routers.site-a.entrypoints=http,https"
        - "traefik.http.routers.site-a.tls=true"
      deploy:
        replicas: 3


  reverse-proxy:
        # The official v2 Traefik docker image
    image: traefik
    # Enables the web UI and tells Traefik to listen to docker
    command: 
       - "--api.insecure=true"
       - "--providers.docker=true"
       - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"

    volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
        - ./certificates:/etc/traefik/certificates
        - ./traefik.yml:/etc/traefik/traefik.yml

# Management UI - Part 1 Optional
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9443:9443"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped