# compose-simple.yml
FROM maven:3.8.3-openjdk-17 AS builder
WORKDIR /app
COPY API/pom.xml .
COPY API/src ./src
RUN mvn clean package -DskipTests

FROM openjdk:latest
WORKDIR /app

COPY --from=builder /app/target/DAI_API-1.0.jar .

EXPOSE 7000
CMD ["java", "-jar", "DAI_API-1.0.jar"]


