package app;

public enum VitaminAndMineral {
    A, B1, B2, B3, B5, B6, B8, B9, B12, C, D, E, K, PP,
    CALCIUM, CHLORINE, CHROMIUM, COPPER, IODINE, IRON,
    MAGNESIUM, MANGANESE, MOLYBDENUM, PHOSPHORUS, POTASSIUM, SELENIUM, SODIUM, ZINC;

}
